apiVersion: v1
kind: Service
metadata:
  name: bitbucket-autoscaler-svc
  labels:
    app: bitbucket-autoscaler
spec:
  type: ClusterIP
  selector:
    app: bitbucket-autoscaler
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
