# apiVersion: v1
# kind: Secret
# metadata:
#   name: {{ .Values.spec.service_name }}-secrets
#   labels:
#     accountUuid: {{ .Values.spec.ACCOUNT_UUID }}
#     runnerUuid: {{ .Values.spec.RUNNER_UUID }}
# data:
#   oauthClientId: {{ .Values.spec.BASE64_OAUTH_CLIENT_ID }}
#   oauthClientSecret: {{ .Values.spec.BASE64_OAUTH_CLIENT_SECRET }}


{{- if .Values.spec.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.spec.service_name }}-repo-secret
type: Opaque
stringData:
  {{- toYaml .Values.spec.secrets.stringData | nindent 2 }}
{{- end }}
