apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bitbucket-autoscaler-external-secret
  namespace: bitbucket-runner
spec:
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: uat/bitbucket-autoscaler
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: secretstore-by-role
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: bitbucket-autoscaler
